// GENERATED by scripts/gen-db-types.mjs — do not edit.
//
// Row types read from the real schema: every migration applied to an in-memory
// SQLite database, then pragma_table_info. Regenerate with:
//
//   node scripts/gen-db-types.mjs
//
// `npm run check:db-types` fails when this drifts, so a renamed column becomes a
// compile error in every handler still selecting the old name — which is exactly
// what `Record<string, unknown>` rows could not do.
//
// A nullable column is `| null` because that is what D1 returns. Use Pick<> to
// describe a projection: a SELECT of three columns is not the whole row, and
// saying so keeps the type honest.

export interface AssessmentResultsRow {
  id: string;
  user_id: string;
  completed_at: string;
  literacy_score: number;
  comprehension_score: number;
  grammar_score: number;
  memorization_score: number;
  level: string;
  details: string;
  path: string | null;
}

export interface GrammarExerciseBankRow {
  id: string;
  kind: string;
  level: number;
  word_arabic: string;
  word_buckwalter: string | null;
  prompt: string;
  answer: string;
  options: string;
  explanation: string;
  surah_id: number;
  ayah_id: number;
  word_index: number;
  segment_index: number;
  root: string | null;
}

export interface GrammarExercisesRow {
  id: string;
  user_id: string;
  exercise_id: string;
  answer: string | null;
  correct: number;
  answered_at: string;
}

export interface GrammarMasteryRow {
  id: number;
  user_id: string;
  category: string;
  mastery_level: number;
  total_attempts: number;
  correct_attempts: number;
  updated_at: string | null;
}

export interface LessonProgressRow {
  user_id: string;
  lesson_id: string;
  module: string;
  completed: number;
  score: number;
  attempts: number;
  last_practiced: string | null;
  next_review: string | null;
  streak: number;
}

export interface LessonsRow {
  id: string;
  title: string;
  module: string;
  level: number;
  content: string;
  exercises: string;
  prerequisites: string;
  estimated_minutes: number;
  category: string | null;
}

export interface MemorizationRow {
  id: string;
  user_id: string;
  surah_id: number;
  ayah_from: number;
  ayah_to: number;
  status: string;
  last_reviewed: string | null;
  next_review: string | null;
  quality: number;
  revision_count: number;
  interval: number;
  ease_factor: number;
  stability: number | null;
  difficulty: number | null;
  last_review: string | null;
  fsrs_state: number | null;
  warm_start: number | null;
}

export interface MemorizationUnitsRow {
  id: string;
  sequence: number;
  level: number;
  surah_id: number;
  ayah_from: number;
  ayah_to: number;
  ayah_count: number;
  surah_name: string;
  rationale: string;
}

export interface QuizAttemptsRow {
  id: string;
  user_id: string;
  lesson_id: string;
  module: string;
  questions_answered: number;
  questions_correct: number;
  time_seconds: number | null;
  completed_at: string;
}

export interface QuranSyntaxRow {
  sentence_id: number;
  token_index: number;
  head_index: number | null;
  surah_id: number;
  ayah_id: number;
  word_index: number;
  segment_index: number;
  rel: string | null;
  rel_ar: string | null;
  constituent: string | null;
  derived_noun: string | null;
  token: string | null;
  is_implied: number;
}

export interface QuranVersesRow {
  surah: number;
  ayah: number;
  text_uthmani: string;
  text_simple: string | null;
  translation: string | null;
  tajweed_tags: string | null;
}

export interface QuranWordGlossRow {
  surah_id: number;
  ayah_id: number;
  position: number;
  arabic: string;
  transliteration: string | null;
  english: string;
}

export interface QuranWordMorphologyRow {
  surah_id: number;
  ayah_id: number;
  word_index: number;
  segment_index: number;
  form: string | null;
  tag: string | null;
  lemma: string | null;
  root: string | null;
  pos: string | null;
  verb_form: string | null;
  aspect: string | null;
  voice: string | null;
  mood: string | null;
  person: string | null;
  gender: string | null;
  number: string | null;
  case_case: string | null;
  state: string | null;
}

export interface QuranWordTimingRow {
  reciter: string;
  surah_id: number;
  ayah_id: number;
  word_index: number;
  start_ms: number;
  end_ms: number;
}

export interface SpacedRepetitionRow {
  id: string;
  user_id: string;
  item_type: string;
  item_id: string;
  interval_days: number;
  ease_factor: number;
  reviews_count: number;
  next_review: string;
}

export interface TajweedPracticeRow {
  id: string;
  user_id: string;
  rule_id: string;
  word_id: string | null;
  correct: number;
  time_spent: number | null;
  practiced_at: string | null;
}

export interface TajweedRulesRow {
  id: string;
  name: string;
  description: string | null;
  color: string;
  color_name: string | null;
}

export interface TutorConversationsRow {
  id: string;
  user_id: string;
  user_message: string;
  assistant_message: string;
  created_at: string;
}

export interface TutorTopicHistoryRow {
  id: string;
  user_id: string;
  topic: string;
  discussed_at: string;
}

export interface UserKnownFunctionWordRow {
  user_id: string;
  lemma: string;
  pos: string;
  first_seen: string;
  strength: number;
}

export interface UserKnownRootRow {
  user_id: string;
  root: string;
  first_seen: string;
  strength: number;
}

export interface UsersRow {
  id: string;
  goal: string;
  onboarding_completed: number;
  current_path: string;
  created_at: string;
  updated_at: string;
  email: string | null;
  name: string | null;
}

export interface VocabularyRow {
  word: string;
  transliteration: string | null;
  meaning: string;
  root: string | null;
  part_of_speech: string | null;
  frequency_rank: number;
}

export interface VocabularyMasteryRow {
  user_id: string;
  word: string;
  meaning_known: number;
  reading_known: number;
  last_seen: string | null;
  next_review: string | null;
  reviews: number;
  ease_factor: number;
  interval_days: number;
  source_surah: number | null;
  source_ayah: number | null;
  source_position: number | null;
  stability: number | null;
  difficulty: number | null;
  last_review: string | null;
  fsrs_state: number | null;
}
