// GENERATED by scripts/gen-assessment.mjs from content/assessments/placement-test.json — do not edit.
//
// 18 questions across 4 modules. Regenerate after editing the JSON.

export interface AssessmentQuestion {
  id: string;
  instruction: string;
  /** Arabic text or glyph to show above the options, if any. */
  display: string | null;
  options: string[];
  correctAnswer: string;
}

export interface AssessmentModule {
  id: string;
  title: string;
  description: string;
  durationMinutes: number | null;
  questions: AssessmentQuestion[];
}

export const ASSESSMENT_MODULES: AssessmentModule[] = [
  {
    "id": "literacy",
    "title": "Arabic Script Literacy",
    "description": "",
    "durationMinutes": 10,
    "questions": [
      {
        "id": "lit-01",
        "instruction": "Which letter is this?",
        "display": "ب",
        "options": [
          "ب (ba)",
          "ت (ta)",
          "ث (tha)",
          "ن (nun)"
        ],
        "correctAnswer": "ب (ba)"
      },
      {
        "id": "lit-02",
        "instruction": "Which letter is this?",
        "display": "م",
        "options": [
          "م (mim)",
          "ن (nun)",
          "ر (ra)",
          "ل (lam)"
        ],
        "correctAnswer": "م (mim)"
      },
      {
        "id": "lit-03",
        "instruction": "Select the correct diacritical marks for: ك _ ت _ ب",
        "display": null,
        "options": [
          "كِتَاب (book)",
          "كَتَبَ (he wrote)",
          "كُتُب (books)",
          "كَتّاب (writers)"
        ],
        "correctAnswer": "كِتَاب (book)"
      },
      {
        "id": "lit-04",
        "instruction": "Read this word: الْكِتَاب",
        "display": null,
        "options": [
          "al-kitāb (the book)",
          "al-kataba (he wrote)",
          "al-kutub (the books)",
          "al-kattāb (the writer)"
        ],
        "correctAnswer": "al-kitāb (the book)"
      },
      {
        "id": "lit-05",
        "instruction": "Which letter is this?",
        "display": "س",
        "options": [
          "س (sin)",
          "ش (shin)",
          "ص (sad)",
          "ز (zay)"
        ],
        "correctAnswer": "س (sin)"
      }
    ]
  },
  {
    "id": "comprehension",
    "title": "Classical Arabic Comprehension",
    "description": "",
    "durationMinutes": 15,
    "questions": [
      {
        "id": "comp-01",
        "instruction": "Read Al-Fatiha and answer: What does 'الرَّحْمَٰنِ الرَّحِيمِ' mean?",
        "display": null,
        "options": [
          "The Entirely Merciful, the Especially Merciful",
          "The Merciful, The Forgiving",
          "The King, The Powerful",
          "The Creator, The Sustainer"
        ],
        "correctAnswer": "The Entirely Merciful, the Especially Merciful"
      },
      {
        "id": "comp-02",
        "instruction": "What does 'مَالِكِ يَوْمِ الدِّينِ' mean?",
        "display": null,
        "options": [
          "Master of the Day of Judgment",
          "King of the Day of Prayer",
          "Creator of the Day of Rest",
          "Lord of the Day of Trial"
        ],
        "correctAnswer": "Master of the Day of Judgment"
      },
      {
        "id": "comp-03",
        "instruction": "What does the Quran say about the Muttaqeen (God-conscious)?",
        "display": null,
        "options": [
          "They are the successful ones",
          "They are the wealthy ones",
          "They are the powerful ones",
          "They are the learned ones"
        ],
        "correctAnswer": "They are the successful ones"
      },
      {
        "id": "comp-04",
        "instruction": "In the verse 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ', what does نَعْبُدُ mean?",
        "display": null,
        "options": [
          "We worship",
          "We ask for help",
          "We guide",
          "We thank"
        ],
        "correctAnswer": "We worship"
      },
      {
        "id": "comp-05",
        "instruction": "What is the main message of Surah Al-Ikhlas?",
        "display": null,
        "options": [
          "The Oneness of God",
          "The Creation of the World",
          "The Day of Judgment",
          "The Prophets' Stories"
        ],
        "correctAnswer": "The Oneness of God"
      }
    ]
  },
  {
    "id": "grammar",
    "title": "Arabic Grammar Knowledge",
    "description": "",
    "durationMinutes": 15,
    "questions": [
      {
        "id": "gram-01",
        "instruction": "Identify the type of noun: كِتَاب",
        "display": null,
        "options": [
          "Definite noun (مَعْرِفَة)",
          "Indefinite noun (نَكِرَة)",
          "Proper noun (عَلَم)",
          "Pronoun (ضَمِير)"
        ],
        "correctAnswer": "Indefinite noun (نَكِرَة)"
      },
      {
        "id": "gram-02",
        "instruction": "What verb pattern is كَتَبَ?",
        "display": null,
        "options": [
          "فَعَلَ (Form I, past tense)",
          "فَاعَلَ (Form II, past tense)",
          "فَعِّلَ (Form III, past tense)",
          "أَفْعَلَ (Form IV, past tense)"
        ],
        "correctAnswer": "فَعَلَ (Form I, past tense)"
      },
      {
        "id": "gram-03",
        "instruction": "In the sentence 'الْكِتَابُ مَفْتُوحٌ', what is the grammatical role of الْمَفْتُوحُ؟",
        "display": null,
        "options": [
          "مبتدأ (subject)",
          "خبر (predicate)",
          "فاعل (doer)",
          "مفعول به (object)"
        ],
        "correctAnswer": "خبر (predicate)"
      },
      {
        "id": "gram-04",
        "instruction": "What is the case ending of the subject in 'جَاءَ الْرَّجُلُ'?",
        "display": null,
        "options": [
          "ـُ (damma — nominative)",
          "ـَ (fatha — accusative)",
          "ـِ (kasra — genitive)"
        ],
        "correctAnswer": "ـُ (damma — nominative)"
      },
      {
        "id": "gram-05",
        "instruction": "Which of these is a sun letter?",
        "display": null,
        "options": [
          "ت",
          "ب",
          "ج",
          "ح"
        ],
        "correctAnswer": "ت"
      }
    ]
  },
  {
    "id": "memorization",
    "title": "Memorization Baseline",
    "description": "",
    "durationMinutes": 10,
    "questions": [
      {
        "id": "mem-01",
        "instruction": "What is the next ayah after: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
        "display": null,
        "options": [
          "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
          "الرَّحْمَٰنِ الرَّحِيمِ",
          "مَالِكِ يَوْمِ الدِّينِ",
          "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ"
        ],
        "correctAnswer": "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ"
      },
      {
        "id": "mem-02",
        "instruction": "Complete: الْحَمْدُ لِلَّهِ رَبِّ ___",
        "display": null,
        "options": [
          "الْعَالَمِينَ",
          "الْرَّحِيمِ",
          "الدِّينِ",
          "الْعَظِيمِ"
        ],
        "correctAnswer": "الْعَالَمِينَ"
      },
      {
        "id": "mem-03",
        "instruction": "What is the last ayah of Surah Al-Ikhlas?",
        "display": null,
        "options": [
          "وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ",
          "اللَّهُ الصَّمَدُ",
          "لَمْ يَلِدْ وَلَمْ يُولَدْ",
          "قُلْ هُوَ اللَّهُ أَحَدٌ"
        ],
        "correctAnswer": "وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ"
      }
    ]
  }
];

export const TOTAL_QUESTIONS = 18;
