/**
 * Generate seed SQL from the files in content/.
 *
 * Writes to stdout so wrangler applies it:
 *
 *   npx tsx scripts/seed-db.ts > /tmp/seed.sql
 *   cd workers && npx wrangler d1 execute languagebuilder --local  --file=/tmp/seed.sql
 *   cd workers && npx wrangler d1 execute languagebuilder --remote --file=/tmp/seed.sql
 *
 * The previous version could not run at all — it did
 * `new Database((globalThis as any).DB)`, which is undefined under tsx — and two
 * of its four steps printed "✅ Seeded N ..." for work they never performed.
 * Steps that are not implemented now say so on stderr instead of claiming
 * success.
 */

import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

/**
 * The user seeded content is attributed to. Must match SINGLE_USER_ID in
 * workers/src/lib/context.ts — this was 'fouad' while the API read
 * 'test-user-1', so seeded vocabulary was invisible and the flashcard queue was
 * always empty.
 */
const SEED_USER_ID = 'test-user-1';

/** Single-quote escaping for SQL string literals. */
const q = (v: unknown): string =>
  v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;

const out: string[] = [];
const note = (msg: string) => process.stderr.write(`${msg}\n`);

async function readJson<T>(...parts: string[]): Promise<T> {
  return JSON.parse(await readFile(join(process.cwd(), ...parts), 'utf-8')) as T;
}

async function main() {
  out.push('-- Generated by scripts/seed-db.ts — do not edit by hand.');
  out.push('');

  // 1. Vocabulary
  const vocabulary = await readJson<Array<{ word: string }>>(
    'content/vocabulary/core-100.json'
  );
  out.push('-- vocabulary_mastery');
  for (const { word } of vocabulary) {
    out.push(
      `INSERT OR IGNORE INTO vocabulary_mastery (user_id, word, meaning_known, reading_known, next_review) ` +
        `VALUES (${q(SEED_USER_ID)}, ${q(word)}, 0, 0, datetime('now'));`
    );
  }
  note(`vocabulary: ${vocabulary.length} words`);

  // 2. Lessons
  type Lesson = {
    id: string;
    title: string;
    module: string;
    level: number;
    content: unknown;
    exercises: unknown;
    prerequisites?: string[];
    estimated_minutes: number;
  };
  const lessons = await readJson<Lesson[]>('content/grammar/lessons.json');
  out.push('');
  out.push('-- lessons');
  for (const l of lessons) {
    out.push(
      `INSERT OR IGNORE INTO lessons (id, title, module, level, content, exercises, prerequisites, estimated_minutes) VALUES (` +
        [
          q(l.id),
          q(l.title),
          q(l.module),
          l.level,
          q(JSON.stringify(l.content)),
          q(JSON.stringify(l.exercises)),
          q(JSON.stringify(l.prerequisites ?? [])),
          l.estimated_minutes,
        ].join(', ') +
        `);`
    );
  }
  note(`lessons: ${lessons.length}`);

  // 3. Assessment questions — NOT SEEDED.
  // content/assessments/placement-test.json holds 18 questions that nothing
  // reads; the app asks 7 hardcoded ones in AssessmentFlow.tsx. Loading this
  // bank is Stage 6, and needs a table to load it into.
  const assessment = await readJson<{ modules: Array<{ questions: unknown[] }> }>(
    'content/assessments/placement-test.json'
  );
  const questionCount = assessment.modules.reduce(
    (n, m) => n + m.questions.length,
    0
  );
  note(
    `assessment: NOT SEEDED — ${questionCount} questions in the bank, no table to load them into yet (Stage 6)`
  );

  // 4. Tajweed rules — already seeded by migration 0001; the six rows the API
  // serves come from there. The richer file below (with subcategories) has no
  // table either.
  const tajweed = await readJson<Array<{ subcategories: unknown[] }>>(
    'content/tajweed/tajweed-rules.json'
  );
  note(
    `tajweed: NOT SEEDED — ${tajweed.length} rules / ` +
      `${tajweed.reduce((n, r) => n + r.subcategories.length, 0)} subcategories in the file; ` +
      `the 6 flat rules the API serves come from migration 0001`
  );

  process.stdout.write(out.join('\n') + '\n');
  note('\nWrote SQL to stdout. Apply it with wrangler d1 execute --file=...');
}

// Not top-level await: there is no package.json "type": "module" at the repo
// root, so tsx transforms this file as CJS, where top-level await is a syntax
// error.
main().catch((err) => {
  note(String(err));
  process.exit(1);
});
